# Generated by Django 4.1.3 on 2022-12-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pghistory', '0005_events_middlewareevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_status', models.CharField(blank=True, choices=[('Owner-Operator', 'Owner-Operator'), ('GA', 'GA'), ('Self Dot', 'Self Dot')], default='Owner-Operator', max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vin_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('plate_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('make', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('registrant', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('registration_start_date', models.DateField(blank=True, default=None, null=True)),
                ('registration_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('inspection_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('state_inspection_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('state_inspection_title_owner', models.DateField(blank=True, default=None, null=True)),
                ('state_inspection_hut_num', models.DateField(blank=True, default=None, null=True)),
                ('state_inspection_ifta_num', models.DateField(blank=True, default=None, null=True)),
                ('physical_damage_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('non_trucking_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('cargo_expiration_date', models.DateField(blank=True, default=None, null=True)),
                ('gps', models.CharField(blank=True, choices=[('Azuga', 'Azuga'), ('Verizon', 'Verizon')], default='Azuga', max_length=50, null=True)),
                ('gps_serial_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('camera', models.CharField(blank=True, choices=[('Azuga', 'Azuga'), ('Verizon', 'Verizon')], default='Azuga', max_length=50, null=True)),
                ('camera_serial_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tablet_imei', models.BooleanField(blank=True, default=None, max_length=50, null=True)),
                ('tablet_owner', models.CharField(choices=[('GA Logistics', 'GA Logistics'), ('Driver', 'Driver')], default='GA Logistics', max_length=50)),
                ('fuel_card', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('card_start_date', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ez_pass_num', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ez_pass_start_date', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rent', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'Need Check'), (2, 'Inactive')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_truck', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_truck', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrucksPlateNumberUpdatedByEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('plate_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plate_number_updated_by_event', to='trucks.trucks')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TruckFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='trucks/%Y-%m-%d/')),
                ('date_created_truck_files', models.DateTimeField(auto_now_add=True)),
                ('truck_files', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.trucks')),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trucks',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trucks_trucksplatenumberupdatedbyevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number", "updated_by_id") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number", NEW."updated_by_id"); RETURN NULL;', hash='9223221cfc4c59f6eec3d0115dcb093b2f99d15f', operation='INSERT', pgid='pgtrigger_snapshot_insert_76437', table='trucks_trucks', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trucks',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."plate_number" IS DISTINCT FROM (NEW."plate_number") OR OLD."updated_by_id" IS DISTINCT FROM (NEW."updated_by_id"))', func='INSERT INTO "trucks_trucksplatenumberupdatedbyevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number", "updated_by_id") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number", NEW."updated_by_id"); RETURN NULL;', hash='aa509b1bff8fa9a72921c7044d915bebcea27381', operation='UPDATE', pgid='pgtrigger_snapshot_update_d1cdc', table='trucks_trucks', when='AFTER')),
        ),
    ]
