# Generated by Django 4.1.3 on 2022-12-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_trucks_state_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='state_inspection',
            field=models.BooleanField(default=False),
        ),
    ]
