# Generated by Django 4.1.3 on 2022-12-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_alter_trucks_state_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='tablet_imei',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
