# Generated by Django 4.1.3 on 2022-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_alter_trucks_tablet_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='rent',
            field=models.IntegerField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No'),
        ),
    ]
