# Generated by Django 4.1.3 on 2022-12-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_alter_trucks_gps_alter_trucks_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='camera',
            field=models.CharField(choices=[('Azuga', 'Azuga'), ('Verizon', 'Verizon')], default='Azuga', max_length=50),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='state_inspection_hut_num',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='state_inspection_ifta_num',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='state_inspection_title_owner',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
