# Generated by Django 4.1.3 on 2022-12-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_alter_trucks_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucks',
            name='fuel_card_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trucks',
            name='who_is_driver',
            field=models.CharField(default='Ga Logistics', max_length=50),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='fuel_card',
            field=models.CharField(choices=[('GA Logistics', 'GA Logistics'), ('Driver', 'Driver')], default='Ga Logistics', max_length=50),
        ),
    ]
