# Generated by Django 4.1.3 on 2022-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0009_trucks_fuel_card_type_trucks_who_is_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucks',
            name='ez_pass',
            field=models.CharField(choices=[('GA Logistics', 'GA Logistics'), ('Driver', 'Driver')], default='Ga Logistics', max_length=50),
        ),
        migrations.AddField(
            model_name='trucks',
            name='who_is_driver_ezpass',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='who_is_driver',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
