# Generated by Django 4.1.3 on 2022-12-09 14:42

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('trucks', '0010_trucks_ez_pass_trucks_who_is_driver_ezpass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckTracker',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('plate_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('registrant', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='trucksplatenumberupdatedbyevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='trucksplatenumberupdatedbyevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='trucksplatenumberupdatedbyevent',
            name='updated_by',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='trucks',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='trucks',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trucks',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trucks_trucktracker" ("owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number", "registrant") VALUES (NEW."owner", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number", NEW."registrant"); RETURN NULL;', hash='dac9e52338a29c49e339469ec13d630329f3415f', operation='INSERT', pgid='pgtrigger_snapshot_insert_76437', table='trucks_trucks', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trucks',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."plate_number" IS DISTINCT FROM (NEW."plate_number") OR OLD."owner" IS DISTINCT FROM (NEW."owner") OR OLD."registrant" IS DISTINCT FROM (NEW."registrant"))', func='INSERT INTO "trucks_trucktracker" ("owner", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number", "registrant") VALUES (NEW."owner", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number", NEW."registrant"); RETURN NULL;', hash='116c5b724eae028d920280ae16852ae621e9fa9f', operation='UPDATE', pgid='pgtrigger_snapshot_update_d1cdc', table='trucks_trucks', when='AFTER')),
        ),
        migrations.DeleteModel(
            name='TrucksPlateNumberUpdatedByEvent',
        ),
        migrations.AddField(
            model_name='trucktracker',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='trucktracker',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plate_number_owner_registrant_event', to='trucks.trucks'),
        ),
    ]
