# Generated by Django 4.1.3 on 2022-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
    ]
