# Generated by Django 4.1.3 on 2022-12-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_driversfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversfiles',
            name='driver_files',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriversFiles',
        ),
    ]
