# Generated by Django 4.1.3 on 2022-12-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_driversfiles_driver_files_delete_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=50)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('zipp', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('license_no', models.IntegerField(blank=True, default=None, null=True)),
                ('license_exp_date', models.DateField(blank=True, default=None, null=True)),
                ('last_medical', models.DateField(blank=True, default=None, null=True)),
                ('next_medical', models.DateField(blank=True, default=None, null=True)),
                ('last_drug_test', models.DateField(blank=True, default=None, null=True)),
                ('next_drug_test', models.DateField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DriversFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/')),
                ('driver_files', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
    ]
