# Generated by Django 4.1.3 on 2022-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='country',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_medical',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='next_medical',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='zipp',
        ),
        migrations.AddField(
            model_name='driver',
            name='ben_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ben_full_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ben_relation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='contract_sign_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AddField(
            model_name='driver',
            name='drug_test_result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drug_test_status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_mvr',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_class',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='med_cert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='med_cert_exp_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='member_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='mvr_status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='occ_exp_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='occ_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_first_send',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_receive_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_second_send',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_charge_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_charge_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_charge_reason',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_received_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_received_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_return_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_returned_amount',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_ein',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
