# Generated by Django 4.1.5 on 2023-01-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driver_address_remove_driver_ben_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_class',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_exp_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issue',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
