# Generated by Django 4.1.5 on 2023-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_drug_test_result_driver_drug_test_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ben_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ben_full_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ben_relation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='clearing_house_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='contract_sign_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_mvr',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='mvr_status',
            field=models.CharField(blank=True, choices=[('Pre-employement', 'Pre-employement'), ('Medical Renewal', 'Medical Renewal'), ('License Renewal', 'License Renewal'), ('After 1 Year', 'After 1 Year')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_first_send',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_receive_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pev_second_send',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='psp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_ein',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='w9_company_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
