# Generated by Django 4.1.5 on 2023-02-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driver_application_fill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
    ]
