# Generated by Django 4.1.5 on 2023-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_remove_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='bank_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='ben_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='drug_test_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='mvr_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='occ_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='pev_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='driversfiles',
            name='w9_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/%Y-%m-%d/'),
        ),
    ]
