# Generated by Django 4.1.3 on 2022-12-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_status', models.CharField(blank=True, choices=[('Owner-Operator', 'Owner-Operator'), ('GA', 'GA'), ('Self Dot', 'Self Dot')], default='Owner-Operator', max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vin_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('plate_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('make', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('registration_start_date', models.DateField(default=None)),
                ('registration_expiration_date', models.DateField(default=None)),
                ('inspection_expiration_date', models.DateField(default=None)),
                ('physical_damage_expiration_date', models.DateField(default=None)),
                ('non_trucking_expiration_date', models.DateField(default=None)),
                ('cargo_expiration_date', models.DateField(default=None)),
                ('gps', models.CharField(blank=True, choices=[('Azuga', 'Azuga'), ('Verizon', 'Verizon')], default='Azuga', max_length=50, null=True)),
                ('gps_serial_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rent', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'Need Check'), (2, 'Inactive')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_trailer', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_trailer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrailerFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='trailers/%Y-%m-%d/')),
                ('date_created_trailer_files', models.DateTimeField(auto_now_add=True)),
                ('trailer_files', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer')),
            ],
        ),
    ]
