# Generated by Django 4.1.5 on 2023-01-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trailer', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trailer_trailertracker" ("cargo_expiration_date", "gps", "gps_serial_number", "id", "inspection_expiration_date", "make", "non_trucking_expiration_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "physical_damage_expiration_date", "plate_number", "registration_expiration_date", "registration_start_date", "rent", "state", "status", "trailer_status", "unit_number", "updated_by_id", "vin_number", "year") VALUES (NEW."cargo_expiration_date", NEW."gps", NEW."gps_serial_number", NEW."id", NEW."inspection_expiration_date", NEW."make", NEW."non_trucking_expiration_date", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."physical_damage_expiration_date", NEW."plate_number", NEW."registration_expiration_date", NEW."registration_start_date", NEW."rent", NEW."state", NEW."status", NEW."trailer_status", NEW."unit_number", NEW."updated_by_id", NEW."vin_number", NEW."year"); RETURN NULL;', hash='206199e368d10d26dd34630aece8731e2aa3f613', operation='INSERT', pgid='pgtrigger_snapshot_insert_1610a', table='trailer_trailer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."trailer_status" IS DISTINCT FROM (NEW."trailer_status") OR OLD."unit_number" IS DISTINCT FROM (NEW."unit_number") OR OLD."vin_number" IS DISTINCT FROM (NEW."vin_number") OR OLD."plate_number" IS DISTINCT FROM (NEW."plate_number") OR OLD."year" IS DISTINCT FROM (NEW."year") OR OLD."state" IS DISTINCT FROM (NEW."state") OR OLD."make" IS DISTINCT FROM (NEW."make") OR OLD."registration_start_date" IS DISTINCT FROM (NEW."registration_start_date") OR OLD."registration_expiration_date" IS DISTINCT FROM (NEW."registration_expiration_date") OR OLD."inspection_expiration_date" IS DISTINCT FROM (NEW."inspection_expiration_date") OR OLD."physical_damage_expiration_date" IS DISTINCT FROM (NEW."physical_damage_expiration_date") OR OLD."non_trucking_expiration_date" IS DISTINCT FROM (NEW."non_trucking_expiration_date") OR OLD."cargo_expiration_date" IS DISTINCT FROM (NEW."cargo_expiration_date") OR OLD."gps" IS DISTINCT FROM (NEW."gps") OR OLD."gps_serial_number" IS DISTINCT FROM (NEW."gps_serial_number") OR OLD."rent" IS DISTINCT FROM (NEW."rent") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."updated_by_id" IS DISTINCT FROM (NEW."updated_by_id"))', func='INSERT INTO "trailer_trailertracker" ("cargo_expiration_date", "gps", "gps_serial_number", "id", "inspection_expiration_date", "make", "non_trucking_expiration_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "physical_damage_expiration_date", "plate_number", "registration_expiration_date", "registration_start_date", "rent", "state", "status", "trailer_status", "unit_number", "updated_by_id", "vin_number", "year") VALUES (NEW."cargo_expiration_date", NEW."gps", NEW."gps_serial_number", NEW."id", NEW."inspection_expiration_date", NEW."make", NEW."non_trucking_expiration_date", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."physical_damage_expiration_date", NEW."plate_number", NEW."registration_expiration_date", NEW."registration_start_date", NEW."rent", NEW."state", NEW."status", NEW."trailer_status", NEW."unit_number", NEW."updated_by_id", NEW."vin_number", NEW."year"); RETURN NULL;', hash='7f58f50cfac477fcd14798870d76b7e1b4e9b330', operation='UPDATE', pgid='pgtrigger_snapshot_update_02dc4', table='trailer_trailer', when='AFTER')),
        ),
    ]
