# Generated by Django 4.1.3 on 2022-12-08 16:00

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerPlateNumberEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('plate_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trailer_trailerplatenumberevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number"); RETURN NULL;', hash='1fc75181d067137c0fffaafe9c75ee160fdd2e8b', operation='INSERT', pgid='pgtrigger_snapshot_insert_1610a', table='trailer_trailer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."plate_number" IS DISTINCT FROM (NEW."plate_number"))', func='INSERT INTO "trailer_trailerplatenumberevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number"); RETURN NULL;', hash='fd055862fe99b10049ffcac90eab2c25bfb62935', operation='UPDATE', pgid='pgtrigger_snapshot_update_02dc4', table='trailer_trailer', when='AFTER')),
        ),
        migrations.AddField(
            model_name='trailerplatenumberevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='trailerplatenumberevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plate_number_event', to='trailer.trailer'),
        ),
    ]
