# Generated by Django 4.1.3 on 2022-12-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trailer', '0004_remove_trailer_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_update',
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='cargo_expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='gps',
            field=models.CharField(blank=True, choices=[('Azuga', 'Azuga'), ('Verizon', 'Verizon')], default='Azuga', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='gps_serial_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='inspection_expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='make',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='non_trucking_expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='physical_damage_expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='rent',
            field=models.BooleanField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'Need Check'), (2, 'Inactive')], default=0),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='trailer_status',
            field=models.CharField(blank=True, choices=[('Owner-Operator', 'Owner-Operator'), ('GA', 'GA'), ('Self Dot', 'Self Dot')], default='Owner-Operator', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='unit_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='vin_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trailertracker',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trailertracker',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='trailer.trailer'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trailer_trailertracker" ("cargo_expiration_date", "created_by_id", "gps", "gps_serial_number", "inspection_expiration_date", "make", "non_trucking_expiration_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "physical_damage_expiration_date", "plate_number", "rent", "state", "status", "trailer_status", "unit_number", "updated_by_id", "vin_number", "year") VALUES (NEW."cargo_expiration_date", NEW."created_by_id", NEW."gps", NEW."gps_serial_number", NEW."inspection_expiration_date", NEW."make", NEW."non_trucking_expiration_date", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."physical_damage_expiration_date", NEW."plate_number", NEW."rent", NEW."state", NEW."status", NEW."trailer_status", NEW."unit_number", NEW."updated_by_id", NEW."vin_number", NEW."year"); RETURN NULL;', hash='2284b44927d847ec781a945bf01593412df01276', operation='INSERT', pgid='pgtrigger_snapshot_insert_1610a', table='trailer_trailer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."trailer_status" IS DISTINCT FROM (NEW."trailer_status") OR OLD."unit_number" IS DISTINCT FROM (NEW."unit_number") OR OLD."vin_number" IS DISTINCT FROM (NEW."vin_number") OR OLD."plate_number" IS DISTINCT FROM (NEW."plate_number") OR OLD."year" IS DISTINCT FROM (NEW."year") OR OLD."state" IS DISTINCT FROM (NEW."state") OR OLD."make" IS DISTINCT FROM (NEW."make") OR OLD."inspection_expiration_date" IS DISTINCT FROM (NEW."inspection_expiration_date") OR OLD."physical_damage_expiration_date" IS DISTINCT FROM (NEW."physical_damage_expiration_date") OR OLD."non_trucking_expiration_date" IS DISTINCT FROM (NEW."non_trucking_expiration_date") OR OLD."cargo_expiration_date" IS DISTINCT FROM (NEW."cargo_expiration_date") OR OLD."gps" IS DISTINCT FROM (NEW."gps") OR OLD."gps_serial_number" IS DISTINCT FROM (NEW."gps_serial_number") OR OLD."rent" IS DISTINCT FROM (NEW."rent") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."created_by_id" IS DISTINCT FROM (NEW."created_by_id") OR OLD."updated_by_id" IS DISTINCT FROM (NEW."updated_by_id"))', func='INSERT INTO "trailer_trailertracker" ("cargo_expiration_date", "created_by_id", "gps", "gps_serial_number", "inspection_expiration_date", "make", "non_trucking_expiration_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "physical_damage_expiration_date", "plate_number", "rent", "state", "status", "trailer_status", "unit_number", "updated_by_id", "vin_number", "year") VALUES (NEW."cargo_expiration_date", NEW."created_by_id", NEW."gps", NEW."gps_serial_number", NEW."inspection_expiration_date", NEW."make", NEW."non_trucking_expiration_date", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."physical_damage_expiration_date", NEW."plate_number", NEW."rent", NEW."state", NEW."status", NEW."trailer_status", NEW."unit_number", NEW."updated_by_id", NEW."vin_number", NEW."year"); RETURN NULL;', hash='235136e786c56bb31ef3ccbae4bee7a312aaee99', operation='UPDATE', pgid='pgtrigger_snapshot_update_02dc4', table='trailer_trailer', when='AFTER')),
        ),
    ]
