# Generated by Django 4.1.3 on 2022-12-09 09:14

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0005_remove_trailer_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='trailer',
            name='snapshot_update',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='cargo_expiration_date',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='gps_serial_number',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='inspection_expiration_date',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='make',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='non_trucking_expiration_date',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='physical_damage_expiration_date',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='state',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='trailer_status',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='unit_number',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='vin_number',
        ),
        migrations.RemoveField(
            model_name='trailertracker',
            name='year',
        ),
        migrations.AlterField(
            model_name='trailertracker',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plate_number_event', to='trailer.trailer'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "trailer_trailertracker" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number"); RETURN NULL;', hash='b2ba00f1668706f7cec06ad7e79629829e8ebed3', operation='INSERT', pgid='pgtrigger_snapshot_insert_1610a', table='trailer_trailer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='trailer',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."plate_number" IS DISTINCT FROM (NEW."plate_number"))', func='INSERT INTO "trailer_trailertracker" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plate_number") VALUES (_pgh_attach_context(), NOW(), \'snapshot\', NEW."id", NEW."plate_number"); RETURN NULL;', hash='97784c86ce809396f59b43926eafc29fdecad858', operation='UPDATE', pgid='pgtrigger_snapshot_update_02dc4', table='trailer_trailer', when='AFTER')),
        ),
    ]
