# Generated by Django 4.1.5 on 2023-03-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_to', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rate', models.IntegerField(blank=True, default=None, null=True)),
                ('truck', models.CharField(default=None, max_length=50)),
                ('trailer', models.CharField(default=None, max_length=50)),
                ('po_number', models.CharField(default=None, max_length=50, unique=True)),
                ('load_status', models.CharField(choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Dispatched', 'Dispatched'), ('Loading', 'Loading'), ('On route', 'On route'), ('Unloading', 'Unloading'), ('In yard', 'In yard')], default='Open', max_length=50)),
                ('notes', models.TextField(default=None, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_load', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_load', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pickup_date_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('pickup_date_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loads.loads')),
            ],
        ),
        migrations.CreateModel(
            name='LoadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='Loads/%Y-%m-%d/')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loads.loads')),
            ],
        ),
        migrations.CreateModel(
            name='LoadDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_drivers', models.CharField(default=None, max_length=50)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loads.loads')),
                ('load_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('delivery_date_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_date_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loads.loads')),
            ],
        ),
    ]
