# Generated by Django 4.1.5 on 2023-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_remove_loaddrivers_load_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddelivery',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadpickup',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
