# Generated by Django 4.1.5 on 2023-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0003_loaddelivery_coordinates_loadpickup_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaddelivery',
            old_name='coordinates',
            new_name='coordinates_delivery',
        ),
        migrations.RenameField(
            model_name='loadpickup',
            old_name='coordinates',
            new_name='coordinates_pickup',
        ),
    ]
