# Generated by Django 4.1.5 on 2023-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_rename_coordinates_loaddelivery_coordinates_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='starting_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
