# Generated by Django 4.1.5 on 2023-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0005_loads_starting_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaddrivers',
            old_name='load_user',
            new_name='load_driver',
        ),
        migrations.AlterField(
            model_name='loaddelivery',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaddelivery', to='loads.loads'),
        ),
        migrations.AlterField(
            model_name='loaddrivers',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaddrivers', to='loads.loads'),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadfiles', to='loads.loads'),
        ),
        migrations.AlterField(
            model_name='loadpickup',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadpickup', to='loads.loads'),
        ),
    ]
