# Generated by Django 4.1.5 on 2023-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0006_rename_load_user_loaddrivers_load_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaddrivers',
            old_name='load_driver',
            new_name='load_driver_user',
        ),
        migrations.RenameField(
            model_name='loaddrivers',
            old_name='load',
            new_name='load_key',
        ),
    ]
