# Generated by Django 4.1.5 on 2023-05-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0007_rename_load_driver_loaddrivers_load_driver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddelivery',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaddeliverys', to='loads.loads'),
        ),
        migrations.AlterField(
            model_name='loadpickup',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadpickups', to='loads.loads'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='LoadCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.CharField(choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Dispatched', 'Dispatched'), ('Loading', 'Loading'), ('On route', 'On route'), ('Unloading', 'Unloading'), ('In yard', 'In yard')], default='Open', max_length=50)),
                ('charges_rate', models.CharField(choices=[('Open', 'Open'), ('Covered', 'Covered'), ('Dispatched', 'Dispatched'), ('Loading', 'Loading'), ('On route', 'On route'), ('Unloading', 'Unloading'), ('In yard', 'In yard')], default='Open', max_length=50)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loadpickup', to='loads.loads')),
            ],
        ),
    ]
