# Generated by Django 4.1.5 on 2023-05-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0009_alter_loadcharges_charges_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaddelivery',
            name='coordinates_delivery',
        ),
        migrations.RemoveField(
            model_name='loadpickup',
            name='coordinates_pickup',
        ),
    ]
