# Generated by Django 4.1.5 on 2023-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0010_remove_loaddelivery_coordinates_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loads',
            name='starting_coordinates',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
