# Generated by Django 4.1.5 on 2023-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0011_alter_loads_starting_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddelivery',
            name='coordinates_delivery',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadpickup',
            name='coordinates_pickup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
