# Generated by Django 4.1.5 on 2023-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0012_loaddelivery_coordinates_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loads',
            name='starting_coordinates',
        ),
        migrations.AddField(
            model_name='loads',
            name='coordinates_starting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loads',
            name='starting_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
